name: poot
description: "Poot smart lock app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_database: ^11.1.6
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.0
  wifi_iot: ^0.3.19+2
  http: ^1.2.2
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
